[package]
name = "rustica"
version = "0.0.1"
edition = "2021"
authors = ["Abdul Basit Ahmad <basit.005@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
num-complex = "0.4.3"

